### ISSUE TITLE
autosplit error

### ISSUE THREAD

**Issue by mslmn** [noaione/nao-manga-rls#4]
When I use the autosplit command I get this error

```
[WARN] Unable to match volume regex, falling back to v00...
[INFO] [?] Processing: 
[ERROR] [00][!] Unable to match chapter: ._002.jpg
[ERROR] [00][!] Exiting...
[ERROR] Failure! (Took 0.01s)
```

My filenames are named p001.jpg, p002.jpg, p003 .jpg etc

**Comment by noaione** [comment]
You should use manualsplit for that, autosplit assumes some specific pattern.
