### ISSUE TITLE
Feature Request: JP Raws Support

### ISSUE THREAD

**Issue by mslmn** [noaione/nao-manga-rls#9]
Is it possible to add support for jp raws to `releases` and `pack`? For example, danke's jp raw releases use the following naming:

Page: `Tonari no Onee-san ga Suki [jpn] - c002 (v01) - p013 [raw-d] [Akita Shoten] [danke-Empire].jpg`
Volume: `Tonari no Onee-san ga Suki v01 (2022) (JPN) (Digital) (danke-Empire)`

**Comment by noaione** [comment]
Available from `v0.15.0`

1. New param: `-ex/--extra-meta`
2. New publication type:
	- `digital-raw`
	- `magazine-raw`

Example:
```py
nmanga pack -t "Tonari no Onee-san ga Suki" -ex "JPN" -y 2022 -pub digital-raw -br round -c "danke-Empire" -vol 1 /target/
```

Produces: `Tonari no Onee-san ga Suki v01 (2022) (JPN) (Digital) (danke-Empire)`

```py
nmanga releases -t "Tonari no Onee-san ga Suki" -pub "Akita Shoten" -ex "JPN" -y 2022 -pub digital-raw -br round -c "danke-Empire"
```

Produces: `Tonari no Onee-san ga Suki - cXXX (vXX) - pXXX [raw-d] [Akita Shoten] [danke-Empire]`

**Comment by noaione** [comment]
> The `[jpn]` after the title is missing from page filenames.

Pushed 0.16.0, should add `jpn` tag to manga title now if you use `--extra-meta`

**Comment by noaione** [comment]
Yeah, there's no option to just make a single volume/oneshot since I don't really archive single volume by myself that much.

I'll probably add the option soon™
